[package]
name = "cesiumdb"
authors = ["Sienna Satterwhite <sienna@linux.com>", "CesiumDB Authors"]
version = "0.0.1"
edition = "2021"

[features]
default_features = []

[dependencies]
libc = "0.2.159"
memmap2 = "0.9.5"
rkyv = { version = "0.8.8", features = ["little_endian"] }
tracing = "0.1.40"
bytes = "1.7.2"
crc32fast = "1.4.2"
bytemuck = { version = "1.19.0" , features = ["extern_crate_alloc", "zeroable_maybe_uninit"]}
