on:
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline

name: Lint

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
